### PR TITLE
IPv6 support for Windows and Linux

### PR DESCRIPTION
**Pull request by WilliamKyle**
Add ipv6 support, tested in Windows 7 and debian 7. I don't have a MAC OS, it is not tested.

PS: 
synergys run as ipv4 mode as default, use -a [::] to turn ipv6 mode.
I don't know how to modify synergy(GUI), so it is now only working start from terminal with args.

### CODE REVIEW

**Comment by davidgro** [comment]
Any update on this? In the last couple weeks I have watched my synergy server PC go through four different IPv4 addresses while keeping the same IPv6, and it is really annoying to change the client settings every time it happens. (The internal DNS is too slow to update to be usable)

**Comment by nbolton** [comment]
@WilliamKyle Just tried to create a branch for you, but seems that I waited too long, so there's a bunch of conflicts. I don't suppose you'd mind solving the conflicts for me? Much appreciated.

**Comment by WilliamKyle** [comment]
@nbolton I am a newbie in github, and I don't know how to update my repo to your latest code. And  I re-installed my computer two months ago, so I have to build the dev environment first. 
I will try to solve the conflicts, but it may takes me some weeks.

**Comment by legonigel** [comment]
@WilliamKyle To learn how to update a fork look at [Syncing a fork](https://help.github.com/articles/syncing-a-fork/). In doing so you will probably encounter some  [merge conflicts](https://help.github.com/articles/resolving-merge-conflicts/) so you will want to read this one about solving them.

**Comment by WilliamKyle** [comment]
@legonigel Thank you so much.

**Comment by WilliamKyle** [comment]
eh... I used cp command to copy patched files to conflict files and pushed to my repo. When I requested a pull, I found the diff of the conflict files become the whole content of the files. So I delete the master of my repo and rollback to the last commit according to an article from the Internet. It seems that this pull request closed automatically, and I can't reopen it even though I pushed the right master to my repo.
@nbolton @legonigel What should I do? Leave this request away and request a new one?

**Comment by nbolton** [comment]
See PR #4499

**Pull request closed without merging**
