### PR TITLE
Add deprecated message on --crypto-pass

### LINKED ISSUE #4570: Make `--crypto-pass` show deprecated message
Problem: The `--crypto-pass` argument is left behind in the registry after a 1.6 to 1.7 upgrade, so when a user upgrades, they need to press 'Apply' in the GUI before it'll work again (not intuitive).

Solution: Give the user a more seamless upgrade by simply showing an "arg deprecated" message when  `--crypto-pass` is used, instead of raising an error and quitting.

----

The upgrade process fails to clear:
--crypto-pass SomeCryptoPass

from:
[HKEY_LOCAL_MACHINE\SOFTWARE\Synergy]
"Command"="\"C:/Program Files/Synergy/synergys.exe\" -f --no-tray --debug INFO --name SomeName  --crypto-pass SomeCryptoPass --ipc --stop-on-desk-switch --enable-drag-drop -c \"D:/SomeUer/Documents/synergy.sgc\" --address :24800"

Resulting in the following error, preventing synergy from starting.
synergys.exe: unrecognized option `--crypto-pass'

This required me to open regedit and manually remove the --crypto-pass option from the "Command" string and restart the synergy service.

### PR DESCRIPTION
**Pull request by legonigel**
Closes #4570.

### CODE REVIEW

**Comment by legonigel** [comment]
Compiled and tested on Linux Mint.

**Comment by speaker** [comment]
Thanks for the pull request! I created a branch for you (https://github.com/synergy/synergy/tree/pr-add-deprecarted-message-on-crypto-pass). I also made small modification to an inadvertent white space change. Buildbot is now [building](http://buildbot.synergy-project.org/builders) (it usually takes about 30 minutes). When done, the packages will be automatically uploaded (http://synergy-project.org/nightly?filter=pr-add-deprecarted-message-on-crypto-pass). Happy testing!

**Comment by legonigel** [comment]
Also, sorry for all the whitespace changes, my editor hates whitespace at the ends of lines. If you want, I can revert those.

**Comment by legonigel** [comment]
@XinyuHou Fixed this in c168721d2f93dd28fc0c78efb5791939c4833e05

**Pull request closed without merging**
