### PR TITLE
Support for Visual Studio 11 and 12

### LINKED ISSUE #4246: Missing support for Visual Studio 12
CMake command: cmake -G "Visual Studio 10" ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:39 (project):
  No CMAKE_C_COMPILER could be found.

I have visual studio 2013 community in my windows 7 64bit.

### PR DESCRIPTION
**Pull request by JoshMcCullough**
Fixed #4246 #4388 #4371

### CODE REVIEW

**Comment by nbolton** [comment]
Is this a duplicate of #4220? Can we combine efforts?

**Comment by JoshMcCullough** [comment]
My changes are a subset of what #4220 does. Mine are simpler, the others include more "in depth" changes. Since my pull request doesn't require difficult merging, you may want to take mine first, and then #4220 and merge it in.

**Comment by nbolton** [comment]
Would you mind splitting the PR into 2 separate fixes so the pbt.h fix is separate?

**Comment by JoshMcCullough** [comment]
Can't really do that, right? Unless I branch and then cherry pick and create new pull requests. Git doesn't have a way to pick certain commits for a pull request AFAIK.

**Comment by beporter** [comment]
Yeah it'd be a little complicated. You'd have to create a two branch names at the tip of your PR branch and then interactively rebase both branches to exclude the commits that should **not** be in each one. Then as a last step, open a second PR for the second branch with the stuff that was pulled out into it.

If your changes aren't cleanly separated into commits, it'd probably be easier to close this PR and re-do the changes into two new branches for two new PRs as Nick is implying.

**Comment by JoshMcCullough** [comment]
Agreed, I can do that...

**Comment by JoshMcCullough** [comment]
Created the following single-issue pull requests: #4413, #4414, #4415, #4416

**Comment by nbolton** [comment]
Excellent, thank you!

**Pull request closed without merging**
