### PR TITLE
Double click breaks dragging and tripple click on Mac

### PR DESCRIPTION
**Pull request by nbolton**
I'm creating a new PR, since I accidentally merged #4261 (oops).

### CODE REVIEW

**Comment by nbolton** [comment]
@jpmcmu Thanks for the pull request! Buildbot is now [building](http://buildbot.synergy-project.org/builders) this PR, which usually takes about 30 minutes. When done, it'll upload the packages to our [nightly builds page](http://synergy-project.org/nightly?filter=pr-jpmcmu-tripple-click-fix). Happy testing!

**Comment by nbolton** [comment]
@jpmcmu Looks like Buildbot is failing because our openssl dirs got wiped out (not your fault). Fixing this now, I'll update when we have some good builds for your PR.

**Comment by nbolton** [comment]
Aaaand I can't remote into the Mac build machine, great. I'll just go ahead and drive over to the office. Should have this fixed in a few hours for you! :)

**Comment by nbolton** [comment]
Hmm, just realized that through my merge/revert rampage, I removed your name from the history (sorry). I'll revert again and cherry-pick your commit so your name shows up. What a mess! Sorry about all that.

**Comment by nbolton** [comment]
Buildbot is now [building](http://buildbot.synergy-project.org/builders) this PR, which usually takes about 30 minutes. When done, it'll upload the packages to our [nightly builds page](http://synergy-project.org/nightly?filter=pr-jpmcmu-tripple-click-fix). Happy testing!

**Comment by nbolton** [comment]
Seems to fail on Mac OS X 10.5 (http://buildbot.synergy-project.org/builders/trunk-mac105/builds/1323).

```

=== BUILD AGGREGATE TARGET ZERO_CHECK OF PROJECT synergy WITH CONFIGURATION Debug ===
Check dependencies
PhaseScriptExecution "CMake Rules" build/synergy.build/Debug/ZERO_CHECK.build/Script-4ECD19762418455AB78F8D6A.sh
    cd /srv/buildbot/synergy/trunk-mac105/build
    /bin/sh -c /srv/buildbot/synergy/trunk-mac105/build/build/synergy.build/Debug/ZERO_CHECK.build/Script-4ECD19762418455AB78F8D6A.sh

echo ""

make -f /srv/buildbot/synergy/trunk-mac105/build/build/CMakeScripts/ReRunCMake.make
make[1]: `/srv/buildbot/synergy/trunk-mac105/build/build/CMakeFiles/cmake.check_cache' is up to date.
2015-03-21 13:42:52.551 xcodebuild[13283:6003] [BT] ASSERTION FAILURE in /SourceCache/DevToolsBase/DevToolsBase-1705/pbxcore/Target.subproj/XCOperationArbitrator.m:374
Details:  Assertion failed: [_runningCommands containsObject:command]
Object:   <XCWorkQueueOperationArbitrator:0x11ddab250>
Method:   -workQueueOperation:commandDidFinish:
Thread:   <NSThread: 0x11dd94ff0>{name = (null), num = 4}
Backtrace:
  0  0x00000001009afd9b -[XCAssertionHandler handleFailureInMethod:object:fileName:lineNumber:messageFormat:arguments:] (in DevToolsCore)
  1  0x00000001009afb1f _XCAssertionFailureHandler (in DevToolsCore)
  2  0x00000001008988a1 -[XCWorkQueueOperationArbitrator workQueueOperation:commandDidFinish:] (in DevToolsCore)
  3  0x000000010088a080 -[XCWorkQueueOperation runOperation] (in DevToolsCore)
  4  0x000000010087a360 -[XCOperation run] (in DevToolsCore)
  5  0x0000000100879baf -[XCOperation runWhenReady] (in DevToolsCore)
  6  0x000000010087d485 -[XCBuildOperation runOperationInBackground] (in DevToolsCore)
  7  0x000000010087cc2c -[XCThreadedOperation _runOperationInBackground] (in DevToolsCore)
  8  0x0000000100070ead __NSThread__main__ (in Foundation)
  9  0x0000000100e8e8b6 _pthread_start (in libSystem.B.dylib)
 10  0x0000000100e8e769 thread_start (in libSystem.B.dylib)
2015-03-21 13:42:52.638 xcodebuild[13283:6003] -runOperationInBackground raised an exception: ASSERTION FAILURE in /SourceCache/DevToolsBase/DevToolsBase-1705/pbxcore/Target.subproj/XCOperationArbitrator.m:374
Details:  Assertion failed: [_runningCommands containsObject:command]
Object:   <XCWorkQueueOperationArbitrator:0x11ddab250>
Method:   -workQueueOperation:commandDidFinish:
Thread:   <NSThread: 0x11dd94ff0>{name = (null), num = 4}
Backtrace:
  0  0x00000001009afd9b -[XCAssertionHandler handleFailureInMethod:object:fileName:lineNumber:messageFormat:arguments:] (in DevToolsCore)
  1  0x00000001009afb1f _XCAssertionFailureHandler (in DevToolsCore)
  2  0x00000001008988a1 -[XCWorkQueueOperationArbitrator workQueueOperation:commandDidFinish:] (in DevToolsCore)
  3  0x000000010088a080 -[XCWorkQueueOperation runOperation] (in DevToolsCore)
  4  0x000000010087a360 -[XCOperation run] (in DevToolsCore)
  5  0x0000000100879baf -[XCOperation runWhenReady] (in DevToolsCore)
  6  0x000000010087d485 -[XCBuildOperation runOperationInBackground] (in DevToolsCore)
  7  0x000000010087cc2c -[XCThreadedOperation _runOperationInBackground] (in DevToolsCore)
  8  0x0000000100070ead __NSThread__main__ (in Foundation)
  9  0x0000000100e8e8b6 _pthread_start (in libSystem.B.dylib)
 10  0x0000000100e8e769 thread_start (in libSystem.B.dylib)
```

**Comment by jpmcmu** [comment]
@nbolton I was able to create a build for Mac OS X 10.5 on my dev machine. From what I can tell the build failure does not seem to be related to the code. Is there anything else I can do to help fix the issue?

**Comment by nbolton** [comment]
Thanks for trying on your 10.5 machine. Its very likely to be our build machine. I'll try a rebuild and get back to you.

**Comment by nbolton** [comment]
Yeah, looks like a random failure, the last one (merged master) built fine.

http://synergy-project.org/files/nightly/synergy-pr-jpmcmu-tripple-click-fix-f80050b-MacOSX105-i386.dmg
http://synergy-project.org/files/nightly/synergy-pr-jpmcmu-tripple-click-fix-f80050b-MacOSX106-i386.dmg

**Comment by nbolton** [comment]
@jankcat Merging :)

**Pull request merged**
