### PR TITLE
Patch for supporting Korean keyboard

### PR DESCRIPTION
**Pull request by twilight512**
Patch for supporting Korean keyboard.
Self tested on Windows 7 and OS X.

### CODE REVIEW

**Comment by twilight512** [comment]
This should solve Issue #3071

**Comment by speaker** [comment]
Thanks for the pull request! I created a branch for you (https://github.com/synergy/synergy/tree/pr-hangul-english-toggle-keyboard-fix). Buildbot is now [building](http://buildbot.synergy-project.org/builders) (it usually takes about 30 minutes). When done, the packages will be automatically uploaded (http://synergy-project.org/nightly?filter=pr-hangul-english-toggle-keyboard-fix). Happy testing!

**Comment by speaker** [comment]
There is a conflict between this change and the change associated with pr-crucifyer-korean-key-fix. https://github.com/synergy/synergy/pull/4475
Can you recommend a combined solution?

**Comment by crucifyer** [comment]
same patch. #4475  :)

**Comment by twilight512** [comment]
They are basically the same patch, but I think you need to also change synergy/src/lib/synergy/key_types.h for full support on other OS's, which is missing in the pr-crucifyer-korean-key-fix patch.

**Comment by speaker** [comment]
Watching #4475  for discussion

**Comment by twilight512** [comment]
I am closing this pull request in support of pulling #4475 as a better solution.

**Pull request closed without merging**
