### PR TITLE
Rename license to LICENSE closes #4487

### LINKED ISSUE #4487: Rename license file to something more logical
Our license file is called "COPYING" which probably has some logic, but perhaps calling it "LICENSE" would make more sense?

### PR DESCRIPTION
**Pull request by legonigel**
Does what the title says, no need to test.

### CODE REVIEW

**Comment by legonigel** [comment]
I just realized I need to rename it in the header of every file. I will fix that.

**Comment by speaker** [comment]
legonigel,

There are a bunch of whitespace changes in src/lib/common/stdsstream.h that don't appear related. Were those intended?

**Comment by legonigel** [comment]
Those weren't intended. I'm still working out my emacs lisp to play nicely with this project. Ill fix it.

**Comment by legonigel** [comment]
@speaker Fixed, just force pushed over the commits. The pull request is automatically updated. 

Also, for future reference, the magical command I used to run this was:
```shell
find . -type f -exec sed -i -e "s/found in the file COPYING that should have accompanied this file/found in the file LICENSE that should have accompanied this file/" {} \;
```

**Comment by legonigel** [comment]
Can this be merged so that I don't have to maintain this? @speaker or @XinyuHou or @nbolton

**Pull request merged**
