### PR TITLE
Add drag and drop enable option to GUI settings

### PR DESCRIPTION
**Pull request by meowfaceman**
This should address [issue 4327](https://github.com/synergy/synergy/issues/4327).

### CODE REVIEW

**Comment by nbolton** [comment]
Thanks for the pull request! Buildbot is now [building](http://buildbot.synergy-project.org/builders) this PR, which usually takes about 30 minutes. When done, it'll upload the packages to our [nightly builds page](http://synergy-project.org/nightly?filter=pr-meowfaceman-gui-drag-drop). Happy testing!

**Comment by meowfaceman** [comment]
Testing this on Windows 7 SP1 seems to work.  The registry key HKLM/SOFTWARE/Synergy/Command changes appropriately when the new drag/drop feature is checked/unchecked, and Synergy behaves as expected.

**Comment by nbolton** [comment]
@meowfaceman Thanks for testing!

**Comment by timkrins** [comment]
Woohoo! Fantastic. Works on Windows 7 SP1 with Windows 8.1 as client.

**Pull request merged**
