### PR TITLE
Mac library path detection for build script

### PR DESCRIPTION
**Pull request by nmadhok**
@nbolton

### CODE REVIEW

**Comment by pr0crast1nate** [comment]
@nbolton I was getting the same issues described in the Synergy wiki with the SDK needing to be set to 10.x. So, that would be generator 1, I suppose.  It might've been helpful to update the wiki with the information from the linked Korean wordpress blog as it was down at the time of my first attempt.

**Comment by nbolton** [comment]
18618d1e39778223b82685d7e2d80dfba5e97c22

**Comment by nbolton** [comment]
Thanks for the pull request! Buildbot is now [building](http://buildbot.synergy-project.org/builders) this PR, which usually takes about 30 minutes. When done, it'll upload the packages to our [nightly builds page](http://synergy-project.org/nightly?filter=pr-nmadhok-mac-lib-build-fix). Happy testing!

**Comment by nbolton** [comment]
This appears to have failed for the Mac OS X 10.8 library (because we use deprecated libs and put them in /Developer/SDKs/). http://buildbot.synergy-project.org/builders/trunk-mac108/builds/1265

I guess we should fall back to the old way if the library isn't found...?

**Comment by nmadhok** [comment]
I'll look into it and make appropriate changes

**Comment by nbolton** [comment]
@nmadhok Thanks!

**Pull request closed without merging**
