### PR TITLE
Fix for ISO C++ ambiguous call on some archs

### PR DESCRIPTION
**Pull request by gtbX**
Had some problems compiling for Sparc/Linux (yeah, widely used combo, I know), this seemed to fix it.  Idk why this is only affecting my sparc machine (gcc 4.8, same as my x86_64 box)

### CODE REVIEW

**Comment by nbolton** [comment]
Thanks for the PR @gtbX!

**Comment by nbolton** [comment]
I excluded the `src/lib/server/ClientProxy1_4.cpp` change since we now use SSL.

**Comment by XinyuHou** [comment]
@gtbX 
It is conflicting now. Could please fix it?

**Comment by gtbX** [comment]
Sorry, I accidentally deleted my original fork.  I re-did the changes and made a new PR here: https://github.com/synergy/synergy/pull/4923

**Pull request closed without merging**
